### ISSUE TITLE
Facing "npm ERR! cb() never called!" while trying to install

### ISSUE THREAD

**Issue by ramalvakonda** [bulyshko/config.json#1]
Running node v0.10.29 and npm v2.0.0-beta.0

Was trying to install the config.json module using "npm install config.json" command and I keep running into the following error. Not sure what's happening. Can someone help?

npm ERR! cb() never called!
npm ERR! not ok code 0

**Comment by bulyshko** [comment]
Hi @ramalvakonda,

Sorry it has taken me so long to reply. Firstly, I was unable to reproduce the issue:

```
~ % node -v
v0.10.29
~ % npm -v
2.0.0-beta.0
~ % npm install config.json
config.json@0.0.3 node_modules/config.json
└── nconf@0.6.9 (ini@1.3.3, async@0.2.9, optimist@0.6.0)
```

Secondly, your problem is not related to `config.json`. I would recommend you to upgrade `npm`.
