### ISSUE TITLE
Lists in json

### ISSUE THREAD

**Issue by MTRNord** [bulyshko/config.json#2]
I had when reading an hson a for loop to get items of lists. with vars with var.["name"].[x].["name"].
Now it says 'unexpected "[" '. How can I get this to work again?

**Comment by bulyshko** [comment]
Hi @MTRNord, could you please give me more details? Please share your config file and the code you're using to read that config file?

**Comment by MTRNord** [comment]
So the script is here: http://pastebin.com/PZUjU6Ra
And the Json for the command.json  is:  http://pastebin.com/Z0Lv7N7z
And the Json for the params.json is: http://pastebin.com/YqzDTLV1

**Comment by bulyshko** [comment]
Well, `config.json` works just fine. Please check your code.

Hint:

```
var prop = 'myprop'
// This is not a valid code:
var name = config.[prop].name;
// Search for ".[" in your code and replace it with "[":
var name = config[prop].name;
```

Hope this helps. I'm closing this issue. Thanks for using `config.json`.

**Comment by MTRNord** [comment]
Ah ok thanks :)
