### ISSUE TITLE
Package no longer installable via NPM

### ISSUE THREAD

**Issue by HoosierWrangler** [bulyshko/config.json#3]
It fails when trying to install ...

NEVERMIND, IT FAILED BECAUSE I HAD A CONFIG.JSON IN THE ROOT OF MY PROJECT ALREADY

**Comment by HoosierWrangler** [comment]
Registry url: https://registry.npmjs.org/
Current Time: 6/14/2016 12:58:39 PM
Last Refreshed: 5/31/2016 1:35:41 PM
Number of Results: 305844
====Executing command 'npm install config.json --save '====

npm ERR! not a package c:\github\OHEP\Server\config.json
npm ERR! addLocal Could not install c:\github\OHEP\Server\config.json
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "config.json" "--save"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path C:\Users\MIKE~1.GRI\AppData\Local\Temp\npm-9164-d489b0ac\unpack-6b39f6f1\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\MIKE~1.GRI\AppData\Local\Temp\npm-9164-d489b0ac\unpack-6b39f6f1\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\MIKE~1.GRI\AppData\Local\Temp\npm-9164-d489b0ac\unpack-6b39f6f1\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Please include the following file with any support request:
npm ERR!     c:\github\OHEP\Server\npm-debug.log

====npm command completed with exit code -4058====

**Comment by bulyshko** [comment]
Please share your npm-debug.log
