### ISSUE TITLE
reload config?

### ISSUE THREAD

**Issue by sascha1337** [bulyshko/config.json#4]
if i do updates to my config.json, how to reload the config that my app responds to that changes without restarting?

**Comment by bulyshko** [comment]
Thank you for your question and sorry it took me so long to respond. [config.json](https://www.npmjs.com/package/config.json) acts only as a wrapper for [nconf](https://www.npmjs.com/package/nconf) to simplify work with environment specific configuration files. You must watch files for changes manually if you expect them to change during the runtime.
