### ISSUE TITLE
how to support list?

### ISSUE THREAD

**Issue by Zapnologica** [bulyshko/config.json#5]
I need to put an array / list of objects in my config file

```
# settings.conf
# Lines beginning with # are skipped when the JSON is parsed, so we can
# put comments into our JSON configuration files
{
	# List Of Upstream Connections
	UpstreamConnections:
	[
		{
			name: "primary"
			serverIp: "127.0.0.1",
			serverPort: "8025",
			devicePort: "8025"				
		},	
		{
			name: "secondary"
			serverIp: "127.0.0.1",
			serverPort: "8025",
			devicePort: "8025"				
		}
	]
}
```
then  i need to iterate through the list in code?

**Comment by bulyshko** [comment]
Thank you for your question and sorry it took me so long to respond. So, let me break it down for you:
1. Comments are not allowed in JSON;
2. Your JSON is not valid;

**Answer to your question:** Yes, you can put a list inside your configuration file and iterate through it later on.
